"""empty message

Revision ID: 0f83c6a7c4f0
Revises: 3a810f59f674
Create Date: 2023-02-08 15:19:06.798699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f83c6a7c4f0'
down_revision = '3a810f59f674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('action', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'resource',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('permissions', 'action')
    # ### end Alembic commands ###
