"""empty message

Revision ID: 3a810f59f674
Revises: ad64609c0b00
Create Date: 2023-02-08 15:11:00.515059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a810f59f674'
down_revision = 'ad64609c0b00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('resource', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('resource', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'permissions', type_='unique')
    # ### end Alembic commands ###
